### ISSUE TITLE
Sync not working in windows environment

### ISSUE THREAD

**Issue by blanquartf** [MashupMill/sync-pom-version-to-package#5]
## Expected Behavior
Version from package.json should be synced with pom.xml  after a sync on Windows

## Current Behavior
An Error is throwed
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

## Steps to Reproduce
yarn run sync-pom-version

**Comment by ammmze** [comment]
Merged in #6 ... should be available soon as version `1.3.1`
